import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

import {  Silkscreen, Bebas_Neue, Exo } from 'next/font/google'
 

// subheading
const silkscreen = Silkscreen({
  subsets: ['latin'],
  variable: '--font-Silkscreen',
  display:'swap',
  weight:'400'
})

// Heading
const BebasNeue = Bebas_Neue({
  subsets: ['latin'],
  variable: '--font-BebasNeue',
  display:'swap',
  weight:'400'
})

// paragraph
const exo = Exo({
  subsets: ['latin'],
  variable: '--font-Exo',
  display:'swap',
  weight:'300'
})

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${silkscreen.variable} ${BebasNeue.variable} ${exo.variable} antialiased sm:py-8 sm:px-24 p-2`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
